;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	autopair-insert-or-skip-quote
	autopair-skip-close-maybe
	c-electric-delete-forward
	coffee-dedent-line-backspace
	cua-copy-region
	cua-cut-region
	cua-delete-region
	cua-paste
	cua-paste-pop
	end-of-buffer
	hungry-delete-forward
	indent-for-tab-command
	indent-new-comment-line
	isearch-exit
	isearch-printing-char
	jjr-end
	jjr-home
	kill-visual-line
	markdown-exdent-or-delete
	match-paren
	org-delete-char
	org-kill-line
	py-indent-line
	ruby-electric-bar
	ruby-electric-close-matching-char
	ruby-electric-curlies
	ruby-electric-matching-char
	ruby-end-space
	ruby-interpolation-insert
	sh-assignment
	smart-tab
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	goto-line
	ido-switch-buffer
	ns-open-file-select-line
	org-self-insert-command
	pager-row-down
	projectile-find-file
	select-window-2
	))
